"use client";

import { useState } from "react";
import Link from "next/link";
import { ChevronLeft, Shield, ChevronRight } from "lucide-react";

export default function PrivacyPolicy() {
  const [currentPage, setCurrentPage] = useState(1);
  const totalPages = 3;

  const next = () => setCurrentPage(prev => Math.min(prev + 1, totalPages));
  const prev = () => setCurrentPage(prev => Math.max(prev - 1, 1));

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-sans py-16 px-6 selection:bg-indigo-500/20 flex flex-col items-center">
      <div className="max-w-4xl w-full">
        <Link href="/" className="inline-flex items-center gap-2 text-indigo-600 font-bold mb-8 hover:text-indigo-800 transition-colors">
          <ChevronLeft className="w-5 h-5" /> Back to Platform
        </Link>
        
        <div className="bg-white p-8 md:p-12 rounded-[32px] shadow-sm border border-slate-200 min-h-[700px] flex flex-col">
          <div className="flex items-center justify-between mb-8">
            <div className="flex items-center gap-4">
              <div className="p-3 bg-indigo-50 rounded-xl">
                <Shield className="w-8 h-8 text-indigo-600" />
              </div>
              <div>
                <h1 className="text-3xl md:text-4xl font-black text-slate-900 tracking-tight">Privacy Policy</h1>
                <p className="text-slate-500 text-sm font-medium mt-1">Effective Date: {new Date().toLocaleDateString()}</p>
              </div>
            </div>
            <div className="px-4 py-1.5 rounded-full bg-slate-100 text-slate-600 text-sm font-bold tracking-widest uppercase">
              Page {currentPage} of {totalPages}
            </div>
          </div>
          
          <div className="text-slate-700 leading-relaxed space-y-6 flex-1 animate-in fade-in duration-500">
            {currentPage === 1 && (
              <div className="space-y-8">
                <section>
                  <h2 className="text-2xl font-bold text-slate-900 mb-4">1. Introduction & Scope</h2>
                  <p className="mb-4">
                    Welcome to PrepAssist. This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                  </p>
                  <p>
                    This comprehensive document is designed to provide complete transparency regarding the data architectures, cloud telemetry, and AI processing pipelines utilized to power your UPSC preparation journey.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-bold text-slate-900 mb-4">2. Interpretation and Definitions</h2>
                  <p className="mb-4">For the purposes of this Privacy Policy:</p>
                  <ul className="list-disc pl-6 space-y-3">
                    <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                    <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to PrepAssist Technologies.</li>
                    <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual, including your email address, name, and OAuth tokens.</li>
                    <li><strong>Study Data</strong> refers to the raw PDFs, images of handwritten essays, and text notes uploaded to the Cloud Vault.</li>
                    <li><strong>Service</strong> refers to the Website, the AI evaluation pipelines, and the RAG infrastructure.</li>
                    <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit or API latency).</li>
                  </ul>
                </section>

                <section>
                  <h2 className="text-2xl font-bold text-slate-900 mb-4">3. Types of Data Collected</h2>
                  <h3 className="text-lg font-bold text-slate-900 mb-2 mt-4">Personal Data</h3>
                  <p className="mb-4">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: Email address, First name and last name, and Usage Data.</p>
                  
                  <h3 className="text-lg font-bold text-slate-900 mb-2 mt-4">Usage Data</h3>
                  <p className="mb-4">Usage Data is collected automatically when using the Service. It may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

                  <h3 className="text-lg font-bold text-slate-900 mb-2 mt-4">Cloud Vault & Study Data</h3>
                  <p>As an AI-driven educational platform, the core of our service relies on processing the documents you upload. When you upload syllabuses, answer sheets, or reference materials, we ingest this data into our secure Firebase storage buckets. This data is strictly partitioned and is explicitly tied to your unique cryptographic User ID.</p>
                </section>
              </div>
            )}

            {currentPage === 2 && (
              <div className="space-y-8">
                <section>
                  <h2 className="text-2xl font-bold text-slate-900 mb-4">4. Use of Your Personal Data</h2>
                  <p className="mb-4">The Company may use Personal Data and Study Data for the following purposes:</p>
                  <ul className="list-disc pl-6 space-y-4">
                    <li><strong>To provide and maintain our Service:</strong> including to monitor the usage of our Service and ensure API uptime.</li>
                    <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
                    <li><strong>For AI Evaluation Execution:</strong> to feed your uploaded handwritten essays into our Computer Vision models for structural grading against UPSC rubrics.</li>
                    <li><strong>For Semantic Indexing (RAG):</strong> to chunk and vectorize your uploaded PDFs so that you can instantly query them using our generative AI chat interfaces.</li>
                    <li><strong>For Credit Ledger Synchronization:</strong> to accurately track the computational weight of your queries and deduct the appropriate number of Credits from your account.</li>
                    <li><strong>To contact You:</strong> To contact You by email, push notifications, or other equivalent forms of electronic communication regarding updates or informative communications related to the functionalities, products or contracted services.</li>
                  </ul>
                </section>

                <section>
                  <h2 className="text-2xl font-bold text-slate-900 mb-4">5. Retention of Your Data</h2>
                  <p className="mb-4">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>
                  <p className="mb-4">Your Study Data (PDFs, Vectors, Notes) will be retained in your active Cloud Vault for as long as your account remains active. If your account is inactive for a period exceeding 24 months, we reserve the right to automatically purge your high-volume vector data to conserve server resources, following a 30-day email notice.</p>
                </section>

                <section>
                  <h2 className="text-2xl font-bold text-slate-900 mb-4">6. Transfer of Your Personal Data</h2>
                  <p className="mb-4">Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located (such as Google Cloud server regions). It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
                  <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.</p>
                </section>
              </div>
            )}

            {currentPage === 3 && (
              <div className="space-y-8">
                <section>
                  <h2 className="text-2xl font-bold text-slate-900 mb-4">7. Third-Party AI Integrations</h2>
                  <p className="mb-4">To provide cutting-edge cognitive capabilities, we securely transmit highly specific portions of your study data to trusted third-party APIs. It is critical to understand the boundaries of these transmissions:</p>
                  <ul className="list-disc pl-6 space-y-4 mb-6">
                    <li><strong>Google Gemini / Vertex AI:</strong> We utilize Google's enterprise-grade LLMs for sophisticated natural language processing, quiz generation, and structural grading of your Mains essays.</li>
                    <li><strong>Pinecone Vector Database:</strong> When you upload a document, we convert the text into mathematical embeddings and store them in Pinecone. This enables instant, semantic search (RAG) across all your uploaded documents.</li>
                  </ul>
                  <div className="p-5 bg-indigo-50/50 rounded-xl border border-indigo-100 mb-6">
                    <p className="text-sm text-indigo-900 font-semibold leading-relaxed">
                      <strong>Zero-Training Guarantee:</strong> Under our enterprise API agreements with Google Cloud and Pinecone, these providers process your data entirely ephemerally to generate responses. Your private study materials, vector embeddings, and evaluation results are <strong>never</strong> used to train, fine-tune, or improve their base public models. Your intellectual property remains securely yours.
                    </p>
                  </div>
                </section>

                <section>
                  <h2 className="text-2xl font-bold text-slate-900 mb-4">8. Security of Your Personal Data</h2>
                  <p className="mb-4">The security of Your Personal Data is deeply important to Us. We utilize Firebase Security Rules to enforce strict access control, ensuring that your Cloud Vault data can only be read by your authenticated session token. All data in transit is encrypted via TLS/SSL, and data at rest is encrypted using industry-standard AES-256 encryption by our cloud providers.</p>
                  <p className="mb-4">However, remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
                </section>

                <section>
                  <h2 className="text-2xl font-bold text-slate-900 mb-4">9. User Rights & Data Deletion Protocol</h2>
                  <p className="mb-4">You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Our Service gives You the ability to delete certain information about You from within the Service.</p>
                  <p className="mb-4">You may update, amend, or delete Your information at any time by signing in to Your Account. When you execute a "Delete Account" action, our backend triggers an automated cascade that permanently purges your Firebase Auth record, your Firestore ledger, your Cloud Storage files, and all associated vectors in Pinecone.</p>
                </section>
                
                <section>
                  <h2 className="text-2xl font-bold text-slate-900 mb-4">10. Contact Us</h2>
                  <p>If you have any questions about this Privacy Policy, You can contact us securely via the Support Widget within the PrepAssist Dashboard or by reaching out to our administrative team.</p>
                </section>
              </div>
            )}
          </div>

          <div className="flex items-center justify-between border-t border-slate-100 mt-8 pt-8">
            <button 
              onClick={prev} 
              disabled={currentPage === 1}
              className="flex items-center gap-2 px-5 py-2.5 rounded-full font-bold text-sm transition-all disabled:opacity-30 disabled:cursor-not-allowed hover:bg-slate-100 text-slate-700"
            >
              <ChevronLeft className="w-4 h-4" /> Previous
            </button>
            
            <div className="flex gap-2">
              {[1, 2, 3].map((page) => (
                <div key={page} className={`w-2 h-2 rounded-full transition-all duration-300 ${currentPage === page ? 'bg-indigo-600 w-6' : 'bg-slate-200'}`} />
              ))}
            </div>

            <button 
              onClick={next} 
              disabled={currentPage === totalPages}
              className="flex items-center gap-2 px-5 py-2.5 rounded-full font-bold text-sm transition-all disabled:opacity-30 disabled:cursor-not-allowed bg-indigo-600 hover:bg-indigo-500 text-white shadow-md shadow-indigo-500/20"
            >
              Next <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
